name = "expp"
version = "0.1.0"
description = "Header-only C++23 library for creating Erlang, Elixir, and Gleam NIFs"
licences = ["MIT"]
repository = { type = "github", user = "woohp", repo = "expp" }

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
