defmodule MyMod do
  @moduledoc """
  Documentation for MyMod.
  """

  use Expp, ext: "./expp"

  def vector_times_int(_v, _i), do: "NIF library not loaded"
  def vector_char_plus_one(_v), do: "NIF library not loaded"
  def vector_int8_plus_one(_v), do: "NIF library not loaded"
  def times2(_m), do: "NIF library not loaded"
  def times4(_t), do: "NIF library not loaded"
  def times5(_i), do: "NIF library not loaded"
  def stringview_identity(_s), do: "NIF library not loaded"
  def variant_int_and_string(_v), do: "NIF library not loaded"
  def bool_arguments(_b), do: "NIF library not loaded"
  def bool_returns(_i), do: "NIF library not loaded"
  def optional_arguments(_i), do: "NIF library not loaded"
  def optional_returns(_i), do: "NIF library not loaded"
  def get_expected(_i), do: "NIF library not loaded"
  def get_expected_stringview_error(_i), do: "NIF library not loaded"
  def atom_arguments(_a), do: "NIF library not loaded"
  def atom_returns(_i), do: "NIF library not loaded"
  def simple_coroutine(_i), do: "NIF library not loaded"
  def nested_vector(_v), do: "NIF library not loaded"
  def ordered_map_test(_m), do: "NIF library not loaded"
  def complex_nested_map(_m), do: "NIF library not loaded"
  def byte_vector_test(_v), do: "NIF library not loaded"
  def make_resource(_i), do: "NIF library not loaded"
  def use_resource(_r), do: "NIF library not loaded"
  def throw_error(_i), do: "NIF library not loaded"
  def dirty_cpu_test(_i), do: "NIF library not loaded"
  def binary_identity(_b), do: "NIF library not loaded"
  def term_identity(_t), do: "NIF library not loaded"
  def raise_runtime_error_test(), do: "NIF library not loaded"
  def multimap_test(_m), do: "NIF library not loaded"
  def unordered_multimap_test(_m), do: "NIF library not loaded"
end
